### ISSUE TITLE
Problem enabling macros

### ISSUE THREAD

**Issue by pimsierhuis** [grblHAL/Plugin_keypad#10]
I'm trying to enable macros but am puzzled by the following issue. I use picocnc board with rp2040 and use the web builder to create firmware. When I use "MACROS_ENABLE=3", the keypad (over serial) works, but $490 gives an error:53 (probably due to AUX input pin shortage). But when I use "MACROS_ENABLE=2" (the way I want to use it), the control-connection over USB stops working! I've looked at macros.c but can't find any explanation. 

Help would be very welcome!

**Comment by pimsierhuis** [comment]
Web Builder json-files attached:

[macro_onlykeypad.json](https://github.com/grblHAL/Plugin_keypad/files/14225577/macro_onlykeypad.json)
[macro_auxandkeypad.json](https://github.com/grblHAL/Plugin_keypad/files/14225578/macro_auxandkeypad.json)

**Comment by terjeio** [comment]
Seems it is due to a memory leak - can you try again now?

**Comment by pimsierhuis** [comment]
It works now. Great, thanks!

For my understanding: memory leak where? In the web builder?

**Comment by terjeio** [comment]
In the macro plugin, bad code on my part. Will commit fix later.

**Comment by pimsierhuis** [comment]
OK, check. Thanks for the quick fix!
