### ISSUE TITLE
Home doesn't work with $22=5

### ISSUE THREAD

**Issue by pimsierhuis** [grblHAL/Plugin_keypad#11]
It seems that if you enable "homing on startup required" (bit 2 of $22), you can't home by sending the H-char over the serial channel to the keypad-plugin.

This is a problem for our use-case where we:
- must home before doing anything else, because we don't have limit switches on all sides (and is desirable anyway)
- Don't have a  streaming g-code sender; we only use http upload to upload a file to SD and use keypad to start the job with a macro containing $F=file

**Comment by terjeio** [comment]
Try with changing [this line](https://github.com/grblHAL/core/blob/c3aace735bdc4e11e256d94a6a78c7810d30000c/protocol.c#L77) to:
`               (state_get() == STATE_IDLE || (state_get() & (STATE_ALARM|STATE_JOG|STATE_TOOL_CHANGE))) &&`

**Comment by terjeio** [comment]
I have committed an update with the above change so I am closing this. Reopen if the issue still persists.

**Comment by pimsierhuis** [comment]
Thanks, great. Already figured out how to compile ourselves, but can't test until tuesday night..

**Comment by pimsierhuis** [comment]
Tested this and it works. Thanks for the fast fix!
